import assert from "node:assert/strict";
import { createDemoApi } from "../src/lib/demo/runtime";
import { isDemoSession } from "../src/lib/demoSession";
import { DEMO_ITEMS, DEMO_LISTINGS, DEMO_RECIPES } from "../src/lib/demo/catalog";
import { DEMO_ITEM_DEFS } from "../src/lib/demo/catalogData";
import { ALL_ITEMS } from "../../api-server/src/lib/itemsData";
const values=new Map<string,string>();
const storage={getItem:(k:string)=>values.get(k)??null,setItem:(k:string,v:string)=>{values.set(k,v);}};
let api=createDemoApi(storage, () => 0);
const request=(path:string,method="GET",body:unknown={})=>api.handle(path,method,body,new URLSearchParams());
assert.equal(isDemoSession(),false,"production compilation cannot enable a demo session");
assert.equal((await (await request('/coins')).json()).balance,5000);
const bought=await request('/shop/buy','POST',{listing_id:1});assert.equal(bought.status,200);
const purchase = await bought.json();
assert.equal(purchase.effective_price, purchase.featured_discount_applied ? 37 : 50);
assert.equal(purchase.new_balance,5000-purchase.effective_price);
assert.equal((await (await request('/user/chests')).json()).mortal,4);
const quantityBefore = api.data.inventory.reduce((sum,item)=>sum+item.quantity,0);
const opened = await (await request('/user/chests/open','POST',{chestType:'mortal'})).json();
assert.equal((await (await request('/user/chests')).json()).mortal,3);
assert.equal(api.data.inventory.reduce((sum,item)=>sum+item.quantity,0),quantityBefore+opened.items.length);
assert.equal(opened.coins_awarded,2);
assert.ok(opened.items.every((item:any)=>DEMO_ITEMS.some(def=>def.name===item.name)));
await request('/user/quests/demo-quest/claim','POST');
assert.equal((await request('/user/quests/demo-quest/claim','POST')).status,409);
await request('/skins/equip','POST',{type:'car',key:'jade'});
await request('/folio','PUT',{state:{projects:[{id:'saved',name:'Saved demo writing',docs:[]}]}});
api=createDemoApi(storage, () => 0);
assert.equal((await (await request('/coins')).json()).balance,5000-purchase.effective_price+2+100);
assert.equal((await (await request('/skins')).json()).equippedCarSkin,'jade');
assert.equal((await (await request('/folio')).json()).state.projects[0].id,'saved');
assert.equal((await request('/unknown/private-action','POST')).status,409);
assert.deepEqual([...values.keys()],["ws.localDemo.data.v3"],"only demo storage is written");
const room=await (await request('/rooms','POST',{mode:'boss',durationMinutes:15,bossWordGoal:2500})).json();
assert.equal(room.mode,'boss');assert.equal(room.timeLeft,900);assert.equal(room.bossWordGoal,2500);
console.log('PASS: production guard, wallet, purchase, chest reward, duplicate claim, persisted skins/writing, isolated storage, unsupported actions, room creation');

await request(`/rooms/${room.code}/writing`, 'PUT', {participantName:'Alex',text:'Saved demo draft'});
assert.equal((await (await request(`/rooms/${room.code}/writing/Alex`)).json()).text,'Saved demo draft');
await request('/user/files','POST',{roomCode:room.code,participantName:'Alex',text:'Saved demo draft'});
assert.equal((await (await request('/folio')).json()).state.projects.find((p:any)=>p.id==='demo-saved-sprints').docs[0].content,'Saved demo draft');
assert.equal((await request('/user/discord','PUT',{enabled:true})).status,409);
console.log('PASS: room draft restore, save sprint to files, no live integration mutations');


// The demo must expose the original economy, not the former three placeholders.
assert.deepEqual(DEMO_ITEM_DEFS, ALL_ITEMS, "demo item names, effects, and values match the real catalog");
const shop=await (await request('/shop')).json();
assert.equal(shop.listings.length,25);
assert.deepEqual(['mortal','earth','heaven'].map(merchant=>shop.listings.filter((item:any)=>item.merchant===merchant).length),[7,11,7]);
assert.equal(shop.listings.find((item:any)=>item.name==='Mortal Chest').price,50);
assert.equal(shop.listings.find((item:any)=>item.name==='Crystal Chest').price,800);
assert.ok(shop.featured && shop.featured.discount_pct===25);
const featured=shop.listings.find((item:any)=>item.id===shop.featured.listing_id);
await request('/demo/wallet/refill','POST');
const discounted=await (await request('/shop/buy','POST',{listing_id:featured.id})).json();
assert.equal(discounted.effective_price,Math.floor(featured.price*.75));
const ironBefore=api.data.chests.iron;
await request('/shop/buy','POST',{listing_id:3});
assert.equal(api.data.chests.iron,ironBefore+3,"bundles grant the full quantity");
await request('/shop/buy','POST',{listing_id:100});
const pill=api.data.inventory.find(item=>item.name==='Body Tempering Pill')!;
const xpBefore=api.data.profile.xp;
const pillCount=pill.quantity;
assert.equal((await request('/user/bag/use','POST',{inventoryId:pill.id})).status,200);
assert.equal(api.data.profile.xp,xpBefore+150);
assert.equal(api.data.inventory.find(item=>item.id===pill.id)?.quantity,pillCount-1);
const walletBeforeSale=api.data.coins;
await request('/coins/sell','POST',{inventory_id:pill.id});
assert.equal(api.data.coins,walletBeforeSale+6);
assert.equal(api.data.inventory.find(item=>item.id===pill.id)?.quantity,pillCount-2);
await request('/shop/buy','POST',{listing_id:120});
const knownWallet=api.data.coins;
assert.equal((await request('/shop/buy','POST',{listing_id:120})).status,409);
assert.equal(api.data.coins,knownWallet,"known recipes never charge demo coins twice");
const recipes=await (await request('/user/crafting/all-recipes')).json();
assert.equal(recipes.length,DEMO_RECIPES.length);
assert.ok(recipes.some((recipe:any)=>recipe.result_name==='Yin-Yang Harmony Pill'&&recipe.is_known));
const common=recipes.find((recipe:any)=>recipe.result_name==='Qi Gathering Pill');
const ingredients=[common.ingredient_1_id,common.ingredient_2_id].map(id=>api.data.inventory.find(item=>item.item_id===id)!);
const ingredientCounts=ingredients.map(item=>item.quantity);
assert.equal((await request('/user/crafting/alchemy','POST',{recipeId:common.id,inventoryIds:[ingredients[0].id,ingredients[0].id]})).status,400);
assert.deepEqual(ingredients.map(item=>api.data.inventory.find(current=>current.id===item.id)?.quantity),ingredientCounts,"invalid ingredients cannot be consumed");
const crafted=await (await request('/user/crafting/alchemy','POST',{recipeId:common.id,inventoryIds:ingredients.map(item=>item.id)})).json();
assert.equal(crafted.success,true);
assert.deepEqual(ingredients.map(item=>api.data.inventory.find(current=>current.id===item.id)?.quantity),ingredientCounts.map(quantity=>quantity-1));
const fusion=api.data.inventory.find(item=>item.name==='Qi Gathering Pill')!;
const beforeFusion=fusion.quantity;
assert.equal((await request('/user/crafting/fusion','POST',{inventoryIds:[fusion.id,fusion.id,fusion.id]})).status,200);
assert.equal(api.data.inventory.find(item=>item.id===fusion.id)?.quantity ?? 0,beforeFusion-3);
await request('/shop/buy','POST',{listing_id:101});
const meridian=api.data.inventory.find(item=>item.name==='Meridian Clearing Pill')!;
await request('/user/bag/use','POST',{inventoryId:meridian.id});
const sprint=api.data.sprints[0];
const xpReward=await (await request('/user/xp','POST',{roomCode:sprint.roomCode})).json();
assert.equal(xpReward.xpGained,sprint.wordCount*2);
assert.equal((await (await request('/user/xp','POST',{roomCode:sprint.roomCode})).json()).xpGained,0);
assert.ok(!api.data.activeEffects.some(effect=>effect.effect_type==='xp_double_next_sprint'));
const durable=JSON.stringify({coins:api.data.coins,inventory:api.data.inventory,known:api.data.knownRecipes});
api=createDemoApi(storage);
assert.equal(JSON.stringify({coins:api.data.coins,inventory:api.data.inventory,known:api.data.knownRecipes}),durable);
console.log('PASS: all three merchants, original catalog/prices, featured discount, chest bundles, pills, selling, recipes, crafting validation, fusion, sprint effects, local persistence');

const legacy=JSON.parse(values.get('ws.localDemo.data.v3')!);
delete legacy.catalogVersion;
legacy.inventory=[{id:1,item_id:1,name:'Spirit Ink',quantity:19,category:'material',rarity:'common',sell_value:10}];
legacy.wishlist={listing_id:3,pinned_at:new Date().toISOString()};
values.set('ws.localDemo.data.v3',JSON.stringify(legacy));
api=createDemoApi(storage);
assert.equal(api.data.inventory[0].quantity,19);
assert.equal(api.data.coins,legacy.coins);
assert.deepEqual(api.data.folio,legacy.folio);
assert.equal(api.data.wishlist?.listing_id,4);
api.save();
const migratedCount=api.data.inventory.length;
api=createDemoApi(storage);
assert.equal(api.data.inventory.length,migratedCount,"catalog migration runs only once");
console.log('PASS: existing demo saves upgraded without losing writing, wallet, or collected items');

const tabA=createDemoApi(storage,()=>0);
const tabB=createDemoApi(storage,()=>0);
const fromTab=(tab:ReturnType<typeof createDemoApi>,path:string,method='GET',body:unknown={})=>tab.handle(path,method,body,new URLSearchParams());
const initialBalance=tabA.data.coins;
const tabPurchase=await (await fromTab(tabA,'/shop/buy','POST',{listing_id:1})).json();
await fromTab(tabB,'/folio','PUT',{state:{projects:[{id:'multitab',name:'Protected writing',docs:[]}]}});
assert.equal((await (await fromTab(tabB,'/coins')).json()).balance,initialBalance-tabPurchase.effective_price);
assert.equal((await (await fromTab(tabA,'/folio')).json()).state.projects[0].id,'multitab');
// Even a stale direct socket-style save only merges fields it changed.
const stale=createDemoApi(storage,()=>0);
const latest=createDemoApi(storage,()=>0);
await fromTab(latest,'/shop/buy','POST',{listing_id:1});
stale.data.drafts['another-room']='Keep this draft';stale.save();
latest.refresh();
assert.equal(latest.data.coins,initialBalance-tabPurchase.effective_price*2);
assert.equal(latest.data.drafts['another-room'],'Keep this draft');
const oldStore={...legacy,coins:999999};values.set('ws.localDemo.data.v1',JSON.stringify(oldStore));
assert.equal(createDemoApi(storage).data.coins,latest.data.coins,'old preview tabs cannot overwrite the migrated store');
console.log('PASS: two-tab purchases, writing, direct socket-style saves, and old-tab isolation');

// A fully current v1 record can equal the baseline in every field. It still
// must be copied whole when there is no v3 record, rather than merging to {}.
const completeV1={...JSON.parse(values.get('ws.localDemo.data.v3')!),coins:4900,drafts:{saved:'Never lose this writing'}};
for(const existingV2 of [null,'{}']) {
  const migrationValues=new Map<string,string>([['ws.localDemo.data.v1',JSON.stringify(completeV1)]]);
  if(existingV2)migrationValues.set('ws.localDemo.data.v3',existingV2);
  const migrationStorage={getItem:(key:string)=>migrationValues.get(key)??null,setItem:(key:string,value:string)=>{migrationValues.set(key,value);}};
  const firstLoad=createDemoApi(migrationStorage);
  const secondLoad=createDemoApi(migrationStorage);
  assert.equal(firstLoad.data.coins,4900);assert.equal(secondLoad.data.coins,4900);
  assert.deepEqual(secondLoad.data.drafts,completeV1.drafts);
  assert.deepEqual(secondLoad.data.sprints,completeV1.sprints);
  assert.equal(JSON.parse(migrationValues.get('ws.localDemo.data.v3')!).coins,4900);
}
console.log('PASS: complete v1 migration and interrupted empty-v3 recovery preserve exact wallet, drafts, and sprints');
