uploads = []
outputs = []

[[generated]]
id = "s7T4knWCkhrbiLJyQ4KWq"
uri = "file://artifacts/desktop-app/resources/icon_new.png"
type = "image"
title = "writing sprint pen icon"

[[generated]]
id = "E24W4wxPsE-rcRCKuLoTn"
uri = "file://artifacts/desktop-app/resources/icon_base.png"
type = "image"
title = "writing sprint fountain pen icon"

[[generated]]
id = "FrcY1zLmK47qXqLAyuQvs"
uri = "file://artifacts/desktop-app/resources/icon_flat.png"
type = "image"
title = "flat white pen nib icon"

[[generated]]
id = "IA6djW54Lju2RchsvuZEP"
uri = "file://artifacts/desktop-app/resources/icon_dark_raw.png"
type = "image"
title = "dark gold pen nib icon"
