// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/slow-bitch/Notification.tsx": () => import("../components/mockups/slow-bitch/Notification.tsx")
};
